[project]
name            = "fzf-py"
version         = "0.1.0"
description     = "Fzf.py - A Pythonic Fzf Wrapper"
readme          = "README.md"
requires-python = ">=3.13"
dependencies    = []

[build-system]
build-backend = "hatchling.build"
requires      = ["hatchling"]
